import { Badge, ImpulseLog, LeaderboardEntry, Profile, UserStats, XPTransaction } from "@/types";

export const demoProfile: Profile = {
  id: "00000000-0000-0000-0000-000000000001",
  name: "Demo User",
  age: 24,
  incomeType: "salary",
  monthlyIncome: 3000,
  monthlyExpenses: 2000,
  city: "Mumbai",
  cityTier: "tier1",
  avatarUrl: "https://api.dicebear.com/8.x/thumbs/svg?seed=demo",
  createdAt: new Date().toISOString(),
};

export const demoStats: UserStats = {
  totalXp: 2450,
  currentStreak: 15,
  longestStreak: 22,
  totalSaved: 2340,
  totalSpentImpulse: 240,
  impulsesResisted: 12,
  impulsesPurchased: 3,
  lastImpulseResistDate: new Date().toISOString(),
  shieldPoints: 4,
};

export const demoImpulseLogs: ImpulseLog[] = [
  {
    id: "iphone",
    itemName: "iPhone 15 Pro",
    itemPrice: 1200,
    category: "electronics",
    decision: "resisted",
    decisionMadeAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    questionsAnswered: { need: "Want", afford: "Yes but tight" },
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    finalAction: "saved",
  },
  {
    id: "nike",
    itemName: "Nike Air Zoom",
    itemPrice: 150,
    category: "fashion",
    decision: "resisted",
    decisionMadeAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    questionsAnswered: { need: "Want", afford: "Yes easily" },
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    finalAction: "saved",
  },
  {
    id: "mouse",
    itemName: "Pro Gaming Mouse",
    itemPrice: 80,
    category: "electronics",
    decision: "delayed",
    delayHours: 24,
    decisionMadeAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    questionsAnswered: { need: "Want", afford: "Yes but tight" },
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "concert",
    itemName: "Concert Ticket",
    itemPrice: 120,
    category: "entertainment",
    decision: "purchased",
    decisionMadeAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    questionsAnswered: { need: "Want", future: "Maybe" },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    finalAction: "bought_later",
  },
  {
    id: "smartwatch",
    itemName: "Smartwatch",
    itemPrice: 400,
    category: "electronics",
    decision: "resisted",
    decisionMadeAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    questionsAnswered: { need: "Want", afford: "No" },
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "jacket",
    itemName: "Leather Jacket",
    itemPrice: 300,
    category: "fashion",
    decision: "resisted",
    decisionMadeAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    questionsAnswered: { need: "Want", similar: "Yes" },
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "headphones",
    itemName: "Wireless Headphones",
    itemPrice: 200,
    category: "electronics",
    decision: "delayed",
    delayHours: 12,
    decisionMadeAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    questionsAnswered: { need: "Want", future: "Maybe" },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sunglasses",
    itemName: "Sunglasses",
    itemPrice: 180,
    category: "fashion",
    decision: "resisted",
    decisionMadeAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    questionsAnswered: { need: "Want", afford: "No" },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoXpTransactions: XPTransaction[] = [
  {
    id: "xp-1",
    amount: 120,
    reason: "Resisted iPhone 15 Pro",
    relatedLogId: "iphone",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "xp-2",
    amount: 15,
    reason: "Streak bonus",
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "xp-3",
    amount: 40,
    reason: "Resisted smartwatch",
    relatedLogId: "smartwatch",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "xp-4",
    amount: 25,
    reason: "Delayed headphones",
    relatedLogId: "headphones",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoBadges: Badge[] = [
  {
    id: "first_resist",
    name: "First Resist",
    description: "Logged your first resisted impulse",
    tier: "bronze",
    earned: true,
    earnedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ten_resists",
    name: "10 Resists",
    description: "Successfully resisted 10 items",
    tier: "silver",
    earned: true,
    earnedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "streak_7",
    name: "7-Day Warrior",
    description: "Maintain a 7-day streak",
    tier: "bronze",
    earned: true,
    earnedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "savings_1000",
    name: "Saved $1000",
    description: "Saved over $1,000 by resisting",
    tier: "silver",
    earned: true,
    earnedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "tech_resister",
    name: "Tech Resister",
    description: "Resisted 10 electronics purchases",
    tier: "gold",
    earned: true,
    earnedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoLeaderboard: LeaderboardEntry[] = [
  { id: "alex", name: "Alex", xp: 3200, streak: 22, rank: 1 },
  { id: "sarah", name: "Sarah", xp: 2800, streak: 18, rank: 2 },
  { id: "00000000-0000-0000-0000-000000000001", name: "Demo User", xp: 2450, streak: 15, rank: 3 },
  { id: "mike", name: "Mike", xp: 1900, streak: 12, rank: 4 },
  { id: "lisa", name: "Lisa", xp: 1600, streak: 9, rank: 5 },
];
